/*
 * File:    elfs-gen.c
 * Author:  Li XianJing <xianjimli@hotmail.com>
 * Brief:   a tool to generate makefile for embeded linux from scratch.
 *
 * Copyright (c) 2009  Li XianJing <xianjimli@hotmail.com>
 *
 * Licensed under the Academic Free License version 2.1
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

/*
 * History:
 * ================================================================
 * 2009-05-29 Li XianJing <xianjimli@hotmail.com> created
 *
 */

#include <ini_config.h>

#define PKGS_DIR "packages"
static void gen_one_pkg(IniGroup* group, FILE* fp);
static void gen_make(IniConfig* ini, FILE* fp);

int main(int argc, char* argv[])
{
	IniConfig* ini = NULL;
	
	if(argc != 2)
	{
		printf("Usage: %s pkg-config\n", argv[0]);

		return 0;
	}

	ini = ini_config_create(argv[1]);
	if(ini != NULL)
	{
		gen_make(ini, stdout);
		ini_config_destroy(ini);
	}

	return 0;
}

static void gen_make(IniConfig* ini, FILE* fp)
{
	IniGroup* group = NULL;
	
	return_if_fail(ini != NULL && ini->groups != NULL && fp != NULL);

	fprintf(fp, "###########################################################################\n");
	fprintf(fp, "# AUTO GENERATED BY ELFS, DO NOT EDIT THIS FILE.                          #\n");
	fprintf(fp, "# Author:   Li XianJing <xianjimli@hotmail.com>                           #\n");
	fprintf(fp, "# HomePage: http://www.limodev.cn/elfs                                    #\n");
	fprintf(fp, "###########################################################################\n\n");

	for(group = ini->groups->first_group; group != NULL; group = group->next)
	{
		gen_one_pkg(group, fp);
	}
	
	fprintf(fp, "all: ");
	for(group = ini->groups->first_group; group != NULL; group = group->next)
	{
		fprintf(fp, " %s", group->name);
	}
	fprintf(fp, "\n	@echo done\n\n");
	
	fprintf(fp, "all_clean: ");
	for(group = ini->groups->first_group; group != NULL; group = group->next)
	{
		fprintf(fp, " %s_clean", group->name);
	}
	fprintf(fp, "\n	@echo clean done\n\n");

	fprintf(fp, "all_source_clean: ");
	for(group = ini->groups->first_group; group != NULL; group = group->next)
	{
		fprintf(fp, " %s_source_clean", group->name);
	}
	fprintf(fp, "\n	@echo source clean done\n\n");

	for(group = ini->groups->first_group; group != NULL; group = group->next)
	{
		IniGroup* next = group->next;
		if(next != NULL)
		{
			fprintf(fp, "%s_start: %s", group->name, group->name);
			for(; next != NULL; next = next->next)
			{
				fprintf(fp, " %s", next->name);
			}
			fprintf(fp, "\n	@echo done\n");
		}
	}

	return ;
}

static const char* get_pkg_tar(const char* url)
{
	const char* start = strrchr(url, '/');

	return start == NULL ? start : start + 1;
}

static const char* get_pkg_dir(const char* pkg_tar, char* dir)
{
	char* end = NULL;
	return_val_if_fail(pkg_tar != NULL && dir != NULL, NULL);

	strcpy(dir, pkg_tar);
	if((end = strstr(dir, ".tar")) != NULL)
	{
		*end = '\0';
	}

	return dir;
}

static void gen_one_pkg(IniGroup* group, FILE* fp)
{
	char buffer[2048] = {0};

	IniPair* url          = ini_pairs_find(group->pairs, "url");
	IniPair* config_env   = ini_pairs_find(group->pairs, "config-env");
	IniPair* config_cmd  = ini_pairs_find(group->pairs, "config-cmd");
	IniPair* config_param = ini_pairs_find(group->pairs, "config-param");
	IniPair* patch_cmd    = ini_pairs_find(group->pairs, "patch-cmd");
	IniPair* download_cmd    = ini_pairs_find(group->pairs, "download-cmd");
	IniPair* config_precmd   = ini_pairs_find(group->pairs, "config-precmd");

	return_if_fail(url != NULL && url->value != NULL);

	const char* tar = get_pkg_tar(url->value);
	const char* dir = get_pkg_dir(tar, buffer);

	fprintf(fp, "%s/%s:\n",              PKGS_DIR, tar);
	if(download_cmd != NULL && download_cmd->value != NULL)
	{
		fprintf(fp, "	cd %s && %s\n", PKGS_DIR, download_cmd->value);
	}
	else
	{
		fprintf(fp, "	cd %s && wget %s\n", PKGS_DIR, url->value);
	}
	fprintf(fp, "%s: %s/%s\n", dir,      PKGS_DIR, tar);
	fprintf(fp, "	tar xf %s/%s\n",     PKGS_DIR, tar);
	fprintf(fp, "%s: %s\n", group->name, dir);

	if(patch_cmd != NULL && patch_cmd->value != NULL)
	{
		fprintf(fp, "	%s && \\\n", patch_cmd->value);
	}

	if(config_env != NULL && config_env->value != NULL)
	{
		fprintf(fp, "	%s && \\\n", config_env->value);
	}

	if(config_precmd != NULL && config_precmd->value != NULL)
	{
		fprintf(fp, "	cd %s && %s; cd -;\\\n", dir, config_precmd->value);
	}

	if(config_cmd == NULL || config_cmd->value == NULL)
	{
		fprintf(fp, "	cd %s && \\\n", dir);
	}
	else if(strcmp(config_cmd->value, "autoconf") == 0)
	{
		fprintf(fp, "	mkdir %s/$(ARCH); cd %s/$(ARCH) && \\\n", dir, dir);
		fprintf(fp, "	../configure $(HOST_PARAM) --prefix=$(PREFIX) %s &&\\\n", 
			config_param != NULL ? config_param->value:"");
	}
	else
	{
		fprintf(fp, "	cd %s && \\\n", dir);
		fprintf(fp, "	./%s %s &&\\\n", config_cmd->value,
			config_param != NULL ? config_param->value:""); 
	}
	fprintf(fp, "	make clean; make && make install\n");
	
	fprintf(fp, "%s_clean:\n", group->name);
	if(config_cmd == NULL || config_cmd->value == NULL)
	{
		fprintf(fp, "	cd %s && make clean\n", dir);
	}
	else if(strcmp(config_cmd->value, "autoconf") == 0)
	{
		fprintf(fp, "	rm -rf %s/$(ARCH)\n", dir);
	}
	else
	{
		fprintf(fp, "	cd %s && make clean\n", dir);
	}

	fprintf(fp, "%s_source_clean:\n", group->name);
	fprintf(fp, "	rm -rf %s\n\n", dir);

	return;
}

